name: Gaffer CI Build

on:
  push:
    paths:
      - "**.cc"
      - "**.hh"
      - "**/meson.build"
      - ".github/workflows/CI.yaml"

  pull_request:
    paths:
      - "**.cc"
      - "**.hh"
      - "**/meson.build"
      - ".github/workflows/CI.yaml"

jobs:
  build:
    name: "Ubuntu Latest"
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:unstable
    steps:
      - uses: actions/checkout@v1
      - name: Install build-time dependencies
        run: |
          apt update
          apt install -y meson
      - name: Build
        run: |
          meson setup build
          ninja -C build
          ninja -C build install
