name: Gaffer CI Build

on:
  push:
    paths:
      - "**.cc"
      - "**.hh"
      - "**/meson.build"
      - ".github/workflows/CI.yaml"

  pull_request:
    paths:
      - "**.cc"
      - "**.hh"
      - "**/meson.build"
      - ".github/workflows/CI.yaml"

jobs:
  meson_gcc:
    name: "Build Gaffer with Meson on Arch Linux (GCC)"
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - name: Install build-time dependencies
        run: |
          pacman --noconfirm --noprogressbar -Syyu
          pacman --noconfirm --noprogressbar -S meson ninja base-devel
      - name: Checkout Gaffer
        uses: actions/checkout@v3
      - name: Generate build files
        run: meson setup build
      - name: Compile
        run: ninja -C build install
